#!/bin/bash

pwd
printenv | fgrep SLURM

cd $SLURM_SUBMIT_DIR
pwd

source ../../../.aifsenv

set -eux

train_end_yyyymmdd=20230905
val_start_yyyymmdd=20230906
val_end_yyyymmdd=20230907

num_channels=1024
num_nodes=$SLURM_NNODES
num_gpus=$((AIFS_NUM_GPUS_PER_NODE * SLURM_NNODES))
num_gpus_per_model=2
ens_size=0
res=o1280
hydra_args="data=zarr_no_insolation"

dataset=aifs-od-an-oper-0001-mars-o1280-2016-2023-6h-v1.zarr

export CUDA_VISIBLE_DEVICES=0,1,2,3
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

jobid=$$
jobname=$SLURM_JOB_NAME

$RAPS_AIFS_ROOT_DIR/bin/train \
    --train-end=$train_end_yyyymmdd --val-start=$val_start_yyyymmdd --val-end=$val_end_yyyymmdd \
    --train-batch-limit=200 --val-batch-limit=0 --max-epochs=1 --ens=$ens_size \
    --num-nodes="$num_nodes" --num-gpus="$num_gpus" --num-workers=6 \
    --num-gpus-per-model="$num_gpus_per_model" -C "$num_channels" \
    --model="transformer" --hidden-res="o96" \
    --dataset="$dataset" --interactive --res="$res" \
    --num-mapper-chunks=4 --num-processor-chunks=2 \
    --hydra-args="$hydra_args" "$@"

exit $?
