#!/bin/bash
pwd
printenv | fgrep SLURM

cd $SLURM_SUBMIT_DIR
pwd

source ../../../.aifsenv

set -eux

train_end_yyyymmdd=20231230
val_start_yyyymmdd=20231231
val_end_yyyymmdd=20231231

num_channels=1024
num_nodes=$SLURM_NNODES
num_gpus=$((AIFS_NUM_GPUS_PER_NODE * SLURM_NNODES))
num_gpus_per_model=1
ens_size=0
res=o800
hydra_args=""

dataset=aifs-benchmarking-ea-an-oper-0001-mars-o800-2023-2023-6h-v1.zarr

export CUDA_VISIBLE_DEVICES=0,1,2,3
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

jobid=$$
jobname=$SLURM_JOB_NAME

$RAPS_AIFS_ROOT_DIR/bin/train \
    --train-end=$train_end_yyyymmdd --val-start=$val_start_yyyymmdd --val-end=$val_end_yyyymmdd \
    --train-batch-limit=90 --val-batch-limit=0 --max-epochs=5 --ens=$ens_size \
    --num-nodes="$num_nodes" --num-gpus="$num_gpus" --num-workers=6 \
    --num-gpus-per-model="$num_gpus_per_model" -C "$num_channels" \
    --model="transformer" --hidden-res="o96" \
    --dataset="$dataset" --interactive --res="$res" \
    --num-mapper-chunks=8 --num-processor-chunks=2 \
    --hydra-args="$hydra_args" "$@"

exit $?
